server:
  port: 8088
spring:
  application:
    name: xtradecustomer
  mvc:
    static-path-pattern: /static/**
  messages:
    basename: errors, messages

logging:
  level:
    root: info
    org:
      springframework:
        security: debug
  logback:
    rollingpolicy:
      file-name-pattern: /var/log/xtrade-web-%d{yyyy-MM-dd}.%i.log
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 100GB

userAccountService:
  url: http://localhost:8090
storeService:
  url: http://localhost:8091

xtrade:
  default:
    url: http://localhost:8088